### ISSUE TITLE
I created on the screen of the seven labels top to bottom, and then move them, each move down one size label position, when the motion to the bottom, the bottom to the top of a moving, keep moving cycle, the question is, when the bottom of a move to the top, then if I change the label content, one hour later, there will be flowerscreen phenomenon, but only if I do not change the content of circulating notes move them, everything is normal, I do not know why this happens, look forward to your reply, thank you

### ISSUE THREAD

**Issue by wangzili** [los-cocos/cocos#234]
look forward to your reply, thank you

**Comment by winkidney** [comment]
I'm sorry, but github is not the platform for you to ask `how to` question.
I watched this project and have received too many notifications from your issue.
Could you read more document  and ask less?Or just ask question by email?
Cocos2d's official document gives perfect example for almost every feature that we will use in our 2d game.Read code sample in `samples` and `tests`  ,you will get more.

**Comment by wangzili** [comment]
I am sorry to disturb you!!!but Ihave try to solve this for many days.thank you for your advise

**Comment by winkidney** [comment]
Mail list below the project home page is a better place for you to get help : )
