### ISSUE TITLE
error 'cannot share context' while import cocos.particle_systems before window creation, with some drivers

### ISSUE THREAD

**Issue by ccanepa** [los-cocos/cocos#235]
error 'cannot share context' while import cocos.particle_systems before calling director.init

seen in mailing lists:
https://groups.google.com/forum/#!topic/cocos-discuss/zg1_Xd7hG6A
https://groups.google.com/forum/#!topic/pyglet-users/44pS-xkoObI

Narrowing the issue by the OPs:

Daniel Gillet:
After some investigation, I found the culprit. It's in particle.py, at line 174:
pic = pyglet.image.load('fire.png', file=pyglet.resource.file('fire.png'))

This is a class attribute, and gets executed at import, before director.init() had a chance to run. Still it's annoying that I need to initialize the director before loading images like this as class attributes.
...
It's actually not pyglet.image.load but texture = pic.get_texture() which is causing problem.
...
(Error seen with IWin 7, py27 or py34, gpu Intel HD Graphics4000 using either pyglet 1.2rc 1 or pyglet 1.2.0 release. )

**Comment by ccanepa** [comment]
lazy loading added in commit c986a04bc3.

Notice the window should be created before instantiating the particle class.

**Comment by dangillet** [comment]
For info, this kind of problem ('Unable to share context') will be soon fixed in Pyglet. See discussion here: https://groups.google.com/forum/#!topic/pyglet-users/44pS-xkoObI
