### ISSUE TITLE
Python interpreter not working with python3

### ISSUE THREAD

**Issue by akiross** [los-cocos/cocos#236]
With cocos 0.6.0, take *samples/hello_world.py*, run it and press *Ctrl+I*.

With python2, the python interpreter console pops up.

With python3 (3.4.1) the program crashes with exception `ImportError: No module named 'layer'`.

Traceback follows.

    Traceback (most recent call last):
      File "hello_world.py", line 30, in <module>
        cocos.director.director.run(main_scene)
      File "/home/username/virtual_env/lib64/python3.4/site-packages/cocos/director.py", line 376, in run
        event_loop.run()
      File "/home/username/virtual_env/lib64/python3.4/site-packages/pyglet/app/base.py", line 136, in run
        self._run_estimated()
      File "/home/username/virtual_env/lib64/python3.4/site-packages/pyglet/app/base.py", line 175, in _run_estimated
        if not platform_event_loop.step(estimate) and estimate != 0.0 and \
      File "/home/username/virtual_env/lib64/python3.4/site-packages/pyglet/app/xlib.py", line 115, in step
        device.select()
      File "/home/username/virtual_env/lib64/python3.4/site-packages/pyglet/canvas/xlib.py", line 165, in select
        dispatch(e)
      File "/home/username/virtual_env/lib64/python3.4/site-packages/pyglet/window/xlib/__init__.py", line 908, in dispatch_platform_event_view
        event_handler(e)
      File "/home/username/virtual_env/lib64/python3.4/site-packages/pyglet/window/xlib/__init__.py", line 1075, in _event_key_view
        self.dispatch_event('on_key_press', symbol, modifiers)
      File "/home/username/virtual_env/lib64/python3.4/site-packages/pyglet/window/__init__.py", line 1154, in dispatch_event
        if EventDispatcher.dispatch_event(self, *args) != False:
      File "/home/username/virtual_env/lib64/python3.4/site-packages/pyglet/event.py", line 355, in dispatch_event
        if handler(*args):
      File "/home/username/virtual_env/lib64/python3.4/site-packages/cocos/director.py", line 176, in on_key_press
        from layer import PythonInterpreterLayer
    ImportError: No module named 'layer'

**Comment by winkidney** [comment]
Have you ever run setup.py?

**Comment by akiross** [comment]
Actually I installed cocos with pip, so I guess setup.py was run.

**Comment by winkidney** [comment]
Could you show me the sys.modules and sys.path?
What is your os?
Where you installed your cocos2d?
Have you ever run `pip install cocos2d` for your python3(or you just installed it for your python2)?

**Comment by akiross** [comment]
I ran `pip2 install cocos2d` and (in virtual environment) `pip3 install cocos2d`, so I should have cocos2d for both versions.

My OS is Linux Fedora 21.

I noticed that this error appears in python3 if I have the `hello_world.py` example outside the source tree, e.g.

    git clone https://github.com/los-cocos/cocos/
    cp cocos/samples/hello_world.py /other/dir/
    cd /other/dir
    python3 hello_world.py # This will crash when pressing Ctrl+I
    python2 hello_world.py # This will not crash

Here's the information you asked. Remeber that python3 installation uses pyvenv.

    $ python2 -c "import sys ; print sys.modules ; print sys.path"
    {'copy_reg': <module 'copy_reg' from '/usr/lib64/python2.7/copy_reg.pyc'>, 'sre_compile': <module 'sre_compile' from '/usr/lib64/python2.7/sre_compile.pyc'>, '_sre': <module '_sre' (built-in)>, 'encodings': <module 'encodings' from '/usr/lib64/python2.7/encodings/__init__.pyc'>, 'site': <module 'site' from '/usr/lib64/python2.7/site.pyc'>, '__builtin__': <module '__builtin__' (built-in)>, 'sysconfig': <module 'sysconfig' from '/usr/lib64/python2.7/sysconfig.pyc'>, '__main__': <module '__main__' (built-in)>, 'encodings.encodings': None, 'abc': <module 'abc' from '/usr/lib64/python2.7/abc.pyc'>, 'posixpath': <module 'posixpath' from '/usr/lib64/python2.7/posixpath.pyc'>, '_weakrefset': <module '_weakrefset' from '/usr/lib64/python2.7/_weakrefset.pyc'>, 'errno': <module 'errno' (built-in)>, 'encodings.codecs': None, 'sre_constants': <module 'sre_constants' from '/usr/lib64/python2.7/sre_constants.pyc'>, 're': <module 're' from '/usr/lib64/python2.7/re.pyc'>, '_abcoll': <module '_abcoll' from '/usr/lib64/python2.7/_abcoll.pyc'>, 'types': <module 'types' from '/usr/lib64/python2.7/types.pyc'>, '_codecs': <module '_codecs' (built-in)>, 'encodings.__builtin__': None, '_warnings': <module '_warnings' (built-in)>, 'genericpath': <module 'genericpath' from '/usr/lib64/python2.7/genericpath.pyc'>, 'stat': <module 'stat' from '/usr/lib64/python2.7/stat.pyc'>, 'zipimport': <module 'zipimport' (built-in)>, '_sysconfigdata': <module '_sysconfigdata' from '/usr/lib64/python2.7/_sysconfigdata.pyc'>, 'mpl_toolkits': <module 'mpl_toolkits' (built-in)>, 'warnings': <module 'warnings' from '/usr/lib64/python2.7/warnings.pyc'>, 'UserDict': <module 'UserDict' from '/usr/lib64/python2.7/UserDict.pyc'>, 'encodings.utf_8': <module 'encodings.utf_8' from '/usr/lib64/python2.7/encodings/utf_8.pyc'>, 'sys': <module 'sys' (built-in)>, 'codecs': <module 'codecs' from '/usr/lib64/python2.7/codecs.pyc'>, 'os.path': <module 'posixpath' from '/usr/lib64/python2.7/posixpath.pyc'>, 'signal': <module 'signal' (built-in)>, 'traceback': <module 'traceback' from '/usr/lib64/python2.7/traceback.pyc'>, 'linecache': <module 'linecache' from '/usr/lib64/python2.7/linecache.pyc'>, 'posix': <module 'posix' (built-in)>, 'encodings.aliases': <module 'encodings.aliases' from '/usr/lib64/python2.7/encodings/aliases.pyc'>, 'exceptions': <module 'exceptions' (built-in)>, 'sre_parse': <module 'sre_parse' from '/usr/lib64/python2.7/sre_parse.pyc'>, 'abrt_exception_handler': <module 'abrt_exception_handler' from '/usr/lib64/python2.7/site-packages/abrt_exception_handler.pyc'>, 'os': <module 'os' from '/usr/lib64/python2.7/os.pyc'>, '_weakref': <module '_weakref' (built-in)>}
    ['', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/home/username/.local/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages', '/usr/lib64/python2.7/site-packages/gst-0.10', '/usr/lib64/python2.7/site-packages/gtk-2.0', '/usr/lib/python2.7/site-packages']

    $ python3 -c "import sys ; print(sys.modules); print(sys.path)"                                                              10:38
    {'sre_constants': <module 'sre_constants' from '/usr/lib64/python3.4/sre_constants.py'>, 'zipimport': <module 'zipimport' (built-in)>, 'marshal': <module 'marshal' (built-in)>, 'encodings.latin_1': <module 'encodings.latin_1' from '/usr/lib64/python3.4/encodings/latin_1.py'>, '_sysconfigdata': <module '_sysconfigdata' from '/usr/lib64/python3.4/_sysconfigdata.py'>, 'io': <module 'io' from '/usr/lib64/python3.4/io.py'>, 'abc': <module 'abc' from '/usr/lib64/python3.4/abc.py'>, 'codecs': <module 'codecs' from '/usr/lib64/python3.4/codecs.py'>, '_weakref': <module '_weakref' (built-in)>, 'encodings': <module 'encodings' from '/usr/lib64/python3.4/encodings/__init__.py'>, '_thread': <module '_thread' (built-in)>, 'site': <module 'site' from '/usr/lib64/python3.4/site.py'>, 'encodings.aliases': <module 'encodings.aliases' from '/usr/lib64/python3.4/encodings/aliases.py'>, '__main__': <module '__main__' (built-in)>, 'os.path': <module 'posixpath' from '/usr/lib64/python3.4/posixpath.py'>, 'posixpath': <module 'posixpath' from '/usr/lib64/python3.4/posixpath.py'>, '_bootlocale': <module '_bootlocale' from '/usr/lib64/python3.4/_bootlocale.py'>, '_frozen_importlib': <module '_frozen_importlib' (frozen)>, 'sre_parse': <module 'sre_parse' from '/usr/lib64/python3.4/sre_parse.py'>, 'copyreg': <module 'copyreg' from '/usr/lib64/python3.4/copyreg.py'>, '_sre': <module '_sre' (built-in)>, '_weakrefset': <module '_weakrefset' from '/usr/lib64/python3.4/_weakrefset.py'>, '_locale': <module '_locale' (built-in)>, 'builtins': <module 'builtins' (built-in)>, 'errno': <module 'errno' (built-in)>, 're': <module 're' from '/usr/lib64/python3.4/re.py'>, '_codecs': <module '_codecs' (built-in)>, '_stat': <module '_stat' (built-in)>, 'sre_compile': <module 'sre_compile' from '/usr/lib64/python3.4/sre_compile.py'>, '_imp': <module '_imp' (built-in)>, 'encodings.utf_8': <module 'encodings.utf_8' from '/usr/lib64/python3.4/encodings/utf_8.py'>, 'sysconfig': <module 'sysconfig' from '/usr/lib64/python3.4/sysconfig.py'>, 'stat': <module 'stat' from '/usr/lib64/python3.4/stat.py'>, 'genericpath': <module 'genericpath' from '/usr/lib64/python3.4/genericpath.py'>, '_io': <module 'io' (built-in)>, 'signal': <module 'signal' (built-in)>, '_warnings': <module '_warnings' (built-in)>, 'posix': <module 'posix' (built-in)>, 'sys': <module 'sys' (built-in)>, '_collections_abc': <module '_collections_abc' from '/usr/lib64/python3.4/_collections_abc.py'>, '_sitebuiltins': <module '_sitebuiltins' from '/usr/lib64/python3.4/_sitebuiltins.py'>, 'os': <module 'os' from '/usr/lib64/python3.4/os.py'>}
    ['', '/usr/lib64/python34.zip', '/usr/lib64/python3.4', '/usr/lib64/python3.4/plat-linux', '/usr/lib64/python3.4/lib-dynload', '/home/username/virtual_env/lib64/python3.4/site-packages', '/home/username/virtual_env/lib/python3.4/site-packages']

**Comment by dangillet** [comment]
I could also reproduce the error.

The problem is in `director.py` line 176. For Python 3, it should be `from cocos.layer import PythonInterpreterLayer`.

I'll make a pull request in a bit to fix that.

**Comment by dangillet** [comment]
Nevermind, this was actually already fixed.

commit 9ab84a275499090173f088c81cf234641a89b8ef
Author: Gereon Kaiping <gereon@veredus>
Date:   Sun Jun 29 12:37:31 2014 +0100

    Replaced an implicit relative import in director.py by an explicit one.
    The implicit relative import does not work in python3, and therefore a cocos app would crash when Ctrl-i was pr
diff --git a/cocos/director.py b/cocos/director.py
--- a/cocos/director.py
+++ b/cocos/director.py
@@ -177,1 +177,1 @@
-            from layer import PythonInterpreterLayer
+            from .layer import PythonInterpreterLayer

For the OP, this change is not yet reflected in the latest release. In order to have this working correctly, you would need to download the last version from github and install it yourself.

**Comment by winkidney** [comment]
Great work:), but when i view the newest code ,it has been fixed.

**Comment by akiross** [comment]
Yes, indeed installing the git version on pip solves the issue `pip3 install git+git://github.com/los-cocos/cocos`

Thanks, sorry for not having checked this before posting.
