### ISSUE TITLE
Cannot run samples

### ISSUE THREAD

**Issue by mzdravkov** [los-cocos/cocos#238]
Every sample, except hello_world, is blowing up with Segmentation fault. The error occurs exactly when a sprite is created (with Sprite('some_img.png'))

I don't have any idea why this may happen, or what information would be valuable for you, so here's a list of something that may be relevant:
OS: 64-bit Manjaro Linux (Arch based)
Python: 3.4.3
I have installed all of the suggested in the installation instructions dependencies (six, pyglet, avbin, sdl, numpy) and have installed cocos2d (version 0.6.3) through pip.
Versions of the dependencies:
six (1.9.0)
pyglet (1.2.2)
A whole bunch of sdl packets: sdl, sdl2, smpeg, sdl_ttf, sdl_mixer, sdl_image, lib32-smpeg, lib32-sdl_mixer, lib32-sdl_image, lib32-sdl2_image, lib32-sdl2, lib32-sdl (won't write the versions of all,  except if you think they are relevant)
numpy (1.9.2)
avbin version 10

**Comment by ccanepa** [comment]
Strange.

To narrow the issue:can you try to run the pyglet script noisy.py, which can be found at examples/noisy/ in the unpacked pyglet source pakage or a pyglet clone from https://bitbucket.org/pyglet/pyglet ?

(in case you run into other types of errors, use a simplified noisy.py dropped in the same location to test a minimal pyglet example, like this. https://gist.github.com/ccanepa/6749680b7fd8f87bddec )

If the simplified script fails, I suggest to post into the pyglet bitbucket issue tracker or in the pyglet mailing list, adding info about your video hardware.

Out of the bat I think a driver issue or pyglet problems with integer coords on some drivers.

**Comment by mzdravkov** [comment]
Yes, both the noisy.py and noisy_simplified.py are giving Segmentation fault. I'll post to pyglet. Thanks for the help.
