### ISSUE TITLE
tiledgrid_actions.py NameError sinz2 not defined

### ISSUE THREAD

**Issue by dossjh** [los-cocos/cocos#241]
on line 426 in tiledgrid_actions.py it reads:
sinz = (math.sin(math.pi + t*math.pi*self.jumps*2 + 0*.01) * self.amplitude * self.amplitude_rate)

it should read:
sinz2 = (math.sin(math.pi + t*math.pi*self.jumps*2 + 0*.01) * self.amplitude * self.amplitude_rate)

**Comment by ccanepa** [comment]
Thanks for the report.

fixed in a47cb99139

Thanks !
