### ISSUE TITLE
AssertionError on tiles.load using .tmx files with non-base64 tiles (xml or csv)

### ISSUE THREAD

**Issue by LukeMS** [los-cocos/cocos#243]
While loading a .tmx file, cocos2d always consider that the tiles inside it are in base64 format (Tiled Map Editor also supports xml and csv formats).
If I try to load a .tmx with .xml formatted tiles, data will become null on line 351 of tiles.py:
> data = decode_base64(data)

The check performed after that fails, and an Assertion Error is raised:
>  File "C:\Python34\lib\site-packages\cocos\tiles.py", line 213, in load
>    obj = load_tmx(filename)
>  File "C:\Python34\lib\site-packages\cocos\tiles.py", line 361, in load_tmx
>    assert len(data) == width * height
>AssertionError

**Comment by ccanepa** [comment]
Ok, added support for layer data variants 'csv', 'xml' and 'base64(uncompressed)' at commit 58f6a20
