### ISSUE TITLE
Rectangular TmxObjects have incorrect position

### ISSUE THREAD

**Issue by ottopotto** [los-cocos/cocos#245]
Hi,

I noticed that TmxObject.fromxml positions rectangular tmx objects too low on the screen. For example, if I place a tile to an object layer, it gets positioned too low by one tile.

The problem seems to be this (tiles.py: [1718](https://github.com/los-cocos/cocos/blob/bcd6e4b56aa03af9df2f1ce70c087f8387b6a632/cocos/tiles.py#L1718)):
`top = map_height - float(tag.attrib['y'])`
From looking at tmx files created with Tiled, `top` won't be the top coordinate, but the bottom coordinate.

Then, lines [1752-1753](https://github.com/los-cocos/cocos/blob/bcd6e4b56aa03af9df2f1ce70c087f8387b6a632/cocos/tiles.py#L1752):
```
if bottom is None:
        bottom = top - h
```
Here `bottom` is set too low.

I tried with a polygon tmx object, and it got positioned correctly. Looks like the function `parse_tmx_points` expects to get the bottom coordinate, as it does.

On the other hand I would expect ellipses and rectangles (without a tile) to get incorrectly positioned too, since their bottom coordinate is set on line 1753 as well.

**Comment by ccanepa** [comment]
Confirmed, thanks for the bug report.

On the Tiled side, 'tile' objects has coords inconsistent with other tiled objects, see https://github.com/bjorn/tiled/issues/91

fixed at commit bcd6e4b by special casing 'tile' objects

**Comment by ottopotto** [comment]
I see. Works well, thanks!

**Comment by bjorn** [comment]
Wrong commit reference, you fixed it in 2c863964c17cea0a07cb893e36d242770677fcf7. :-)

And just know that as time goes by, I'm increasingly sorry for having introduced this inconsistency. I'll get it fixed eventually, and then all these libraries will have to be fixed once again. :-(

**Comment by ccanepa** [comment]
don't worry, not a big deal
