### ISSUE TITLE
Mouse Sprite

### ISSUE THREAD

**Issue by vyscond** [los-cocos/cocos#251]
I've research and didn't find how can i change the mouse pointer sprite/image or just hide him with cocos, but i found how to do with pyglet

```python
window = pyglet.window.Window()
image = pyglet.image.load('assets/imgs/cursor_gauntlet.gif')
cursor = pyglet.window.ImageMouseCursor(image, 16, 8)
window.set_mouse_cursor(cursor)
```

Apply this with hello world example

```python
import cocos
import pyglet

class MouseDisplay(cocos.layer.Layer):
    is_event_handler = True     #: enable director.window events

    def __init__(self):
        super(MouseDisplay, self ).__init__()
        self.sprite = cocos.sprite.Sprite('assets/imgs/cursor_gauntlet.gif')
        self.add(self.sprite)
        self.posx = 100
        self.posy = 340
        self.text = cocos.text.Label('No mouse events yet', font_size=18, x=self.posx, y=self.posy )
        self.add( self.text )

    def update_text (self, x, y):
        text = 'Mouse @ %d,%d' % (x, y)
        self.text.element.text = text
        self.text.element.x = self.posx
        self.text.element.y = self.posy

    def on_mouse_motion (self, x, y, dx, dy):
        """Called when the mouse moves over the app window with no button pressed

        (x, y) are the physical coordinates of the mouse
        (dx, dy) is the distance vector covered by the mouse pointer since the
          last call.
        """
        self.update_text (x, y)
        self.sprite.position = x, y

class HelloWorld(cocos.layer.Layer):
    def __init__(self):
        super(HelloWorld, self).__init__()
        label = cocos.text.Label(
            'Hello World',
            font_name='Times New Roman',
            font_size=32,
            anchor_x='center',
            anchor_y='center'
        )
        label.position = 320, 240
        self.add(label)

window = pyglet.window.Window()
image = pyglet.image.load('assets/imgs/cursor_gauntlet.gif')
cursor = pyglet.window.ImageMouseCursor(image, 16, 8)
window.set_mouse_cursor(cursor)

cocos.director.director.init()
cocos.director.director.run(cocos.scene.Scene(HelloWorld(), MouseDisplay()))
```

spawn two identical windows. So how can i manage this?

**Comment by ccanepa** [comment]
On Wed, Sep 23, 2015 at 8:17 PM, Ramon Moraes <notifications@github.com>
wrote:

> I've research and didn't find how can i change the mouse pointer
> sprite/image or just hide him with cocos, but i found how to do with pyglet
>
> window = pyglet.window.Window()
> image = pyglet.image.load('assets/imgs/cursor_gauntlet.gif')
> cursor = pyglet.window.ImageMouseCursor(image, 16, 8)
> window.set_mouse_cursor(cursor)
>
> Apply this with hello world example
>
> import cocos
> import pyglet
>
> class MouseDisplay(cocos.layer.Layer):
>     is_event_handler = True     #: enable director.window events
>
>     def __init__(self):
>         super(MouseDisplay, self ).__init__()
>         self.sprite = cocos.sprite.Sprite('assets/imgs/cursor_gauntlet.gif')
>         self.add(self.sprite)
>         self.posx = 100
>         self.posy = 340
>         self.text = cocos.text.Label('No mouse events yet', font_size=18, x=self.posx, y=self.posy )
>         self.add( self.text )
>
>     def update_text (self, x, y):
>         text = 'Mouse @ %d,%d' % (x, y)
>         self.text.element.text = text
>         self.text.element.x = self.posx
>         self.text.element.y = self.posy
>
>     def on_mouse_motion (self, x, y, dx, dy):
>         """Called when the mouse moves over the app window with no button pressed
>
>         (x, y) are the physical coordinates of the mouse
>         (dx, dy) is the distance vector covered by the mouse pointer since the
>           last call.
>         """
>         self.update_text (x, y)
>         self.sprite.position = x, y
>
> class HelloWorld(cocos.layer.Layer):
>     def __init__(self):
>         super(HelloWorld, self).__init__()
>         label = cocos.text.Label(
>             'Hello World',
>             font_name='Times New Roman',
>             font_size=32,
>             anchor_x='center',
>             anchor_y='center'
>         )
>         label.position = 320, 240
>         self.add(label)
>
>
don't instantiate directly the pyglet window; the cocos director will do
and then you access the window through director.


>
>
> window = pyglet.window.Window()
> image = pyglet.image.load('assets/imgs/cursor_gauntlet.gif')
> cursor = pyglet.window.ImageMouseCursor(image, 16, 8)
> window.set_mouse_cursor(cursor)
>
> cocos.director.director.init()
>
> here the director has the pyglet window, accessible by
cocos.director.director.window


> cocos.director.director.run(cocos.scene.Scene(HelloWorld(), MouseDisplay()))
>
> spawn two identical windows. So how can i manage this?
>

So, deleting the direct pyglet window creation, reordering and  adding
'from cocos.director import director' in the import area to not have too
long names, the block after the classes looks as that:

director.init()
image = pyglet.image.load('grossini.png')
cursor = pyglet.window.ImageMouseCursor(image, 16, 8)
director.window.set_mouse_cursor(cursor)
director.run(cocos.scene.Scene(HelloWorld(), MouseDisplay()))

Tested, it works.

**Comment by vyscond** [comment]
Thanks mate! I will test

**Comment by ccanepa** [comment]
closing, assumed solved.
