### ISSUE TITLE
ScrollingManager scale makes the image jitter

### ISSUE THREAD

**Issue by dangillet** [los-cocos/cocos#253]
In commit 7f5236f150  - in branch scrolling_manager- , I created a test showing that when zooming in with the ScrollingManager, the movement is not smooth.

**Comment by dangillet** [comment]
Commit e2d77d358 offers a solution.

**Comment by dangillet** [comment]
Although quite old, this problem was apparently already observed before here:
- https://groups.google.com/forum/#!searchin/cocos-discuss/zoom$20layer/cocos-discuss/hGfYF5CF62Q/_J5Ln4d6v64J 
- https://groups.google.com/forum/#!searchin/cocos-discuss/zoom$20layer/cocos-discuss/q3qaj_4UNXg/2Mu6QKm0BK0J

**Comment by ccanepa** [comment]
Confirmed the defect in the OP.

Confirmed the second commit produces smooth change.

Theres the possibility that tilemaps show cracks with this change, but it will be a call to fix another problem (ancient scrolling code was not meant to allow scale, so int focus + int sprite coords ensured final int screen coords for sprite vertices, ensuring consistent sampling position  )

I suggest landing the change on master, and later fix problems if they appear.

Formalities:
I wouldn't include the bugdemo in master: test/ has enough samples, and this will not show anything new to users.

In general, bugdemos that are pure code (meaning not extra files needed besides the ones found in test/) can be included in an issue by making a gist and linking from the issue; for bugdemos that require extra files or are a number of scripts, a directory can be created on los-cocos/etc_code repo and mentioned in the los-cocos/cocos issue

**Comment by dangillet** [comment]
Ok. I finally found some time to make the necessary changes. So I created a [gist with the test showing the problem](https://gist.github.com/dangillet/791103fa70c9182988ff).

I pushed the changes on master, and not the test as you suggested. I updated the CHANGELOG accordingly.

Should I also erased the branch (scrolling_manager](https://github.com/los-cocos/cocos/tree/scrolling_manager) ?

Finally I'm closing this ticket.

**Comment by ccanepa** [comment]
On Thu, Oct 22, 2015 at 9:54 AM, Daniel Gillet <notifications@github.com>
wrote:

> Ok. I finally found some time to make the necessary changes. So I created
> a gist with the test showing the problem
> <https://gist.github.com/dangillet/791103fa70c9182988ff>.
>
> I pushed the changes on master, and not the test as you suggested. I
> updated the CHANGELOG accordingly.
>

Great!
