### ISSUE TITLE
After a scene trasition the active scene still has the transition as parent, should be None

### ISSUE THREAD

**Issue by dangillet** [los-cocos/cocos#254]
When using `director.replace(FadeTransition(cocos.scene.Scene(MyLayer()), 2))`, when the transition finishes, the new scene parent is still set to the *Envelope Scene* from the *SceneTransition* object. This prevents the transition and all related children to be garbage collected. See discussion: https://groups.google.com/forum/#!topic/cocos-discuss/I7c-vtclP-Y

**Comment by dangillet** [comment]
A fix is available in dc13be6270. I've added some basic tests.

Also I noticed that to be complete, it was required to remove the director current scene from its parent children list.

**Comment by ccanepa** [comment]
I see the 'completeness' as in
  - separating two subgraphs
  - so it can be said ' any node in an inactive scene is not active'

In practical terms I'm not sure how much it buys:
  - Absolute majority of use cases for scene-into-a-scene is a transition when the parent is discarded after becoming inactive, so the remove buys nothing
  - If the user keeps the parent after the transition to fiddle with it, how you know it wants the child removed ? Why it can't be explicit then ?

The price for the completeness is code not so immediate as the no frills version, compare:
```python
        self.scene = scene

            # always true except when terminating the app
	        if self.scene is not None:
	            if self.scene.parent:
	                # If this scene has a parent, break the
	                # parent - child relationship. Running
	                # scene is always the toplevel node.
	                self.scene.parent.remove(self.scene)
	                self.scene.parent = None
	            self.scene.enable_handlers(True)
	            scene.on_enter()
```
with
```python
        self.scene = scene

        # always true except when terminating the app
        if scene is not None:
			# active scene is the top node
			scene.parent = None
            scene.enable_handlers(True)
            scene.on_enter()
```
If you really want the long functionality, then it could be rewriting similar to

```python
        self.scene = scene

		# always true except when terminating the app
		if self.scene is not None:
			if self.scene.parent is not None:
				# defensive programming
				self.scene.parent.remove(self.scene)
			# active scene is the top node
			self.scene.parent = None
			self.scene.enable_handlers(True)
			scene.on_enter()

``` 
The remove was de-enphatized, it is immediate that the new active scene will always have parent None without following the flow in the ifs

Its your call.

**Comment by dangillet** [comment]
Hi,

I see your point. But I noticed that in my `test_2_pop`, when I push the `scene_child` its parent is set to None, which is what we want. But when I pop the `scene_child`, the `scene_parent` comes back as the current scene and its `on_enter` method is called, in which we find:
```python
for c in self.get_children():
    c.parent = self
```

I'm not saying it's a problem, but I was caught by this behaviour. Is this what we want ? Maybe... In the meantime I made some changes that you can find in commit 7fa42e8.

I had also to add one *OpenGL* mock function in the *pyglet_mockup1* as the `glTranslatef` function was getting called on the children of the current scene.

**Comment by dangillet** [comment]
Any comments on previous message ? Is it good to merge to master ?

**Comment by ccanepa** [comment]
I think the tests need work, they are hard to read at the moment (and the pop test is wrong)

- the lines director.pop and director.push should be removed, the actions are performed by the lines director.on_pop and director.on_push

- As the docstring you wrote for the tests says, we want to assert whenever a scene becomes the active scene, then his .parent member is set to None. No mention here of scene children

- So, don't call the scenes in the tests scene_parent and scene_child, and don't add a scene as a child of the other.  new_scene and, if necessary, old_scene seems more appropriate names

- Just before calling the change under test, set a non None value in .parent of the scene that will become active, then do the scene change, then assert. 

- As .parent is a property that really stores a WeakRef, an obvious value like 'not None value' can't be used. Outside the test class it can be set
```python
class NotNone(object):
    pass
not_None_value = NotNone()  
```

- By example, the pop test will look as

```python
    def test_2_pop(self):
        old_scene = Scene()
        new_scene = Scene()

        director.run(old_scene)
        director.on_push(new_scene)
        # pyglet mockup 1 don't tickle on_draw, we call
        # directly so the push / pop operation completes
        director.on_draw()

        old_scene.parent = not_None_value
        director.on_pop()
        # pyglet mockup 1 don't tickle on_draw, we call
        # directly so the push / pop operation completes
        director.on_draw()

        assert old_scene.parent is None
```  

- If you want, I can rewrite the tests, just let me know.

**Comment by dangillet** [comment]
Hi Claudio,

Thanks for all these info. I understand better how you want to achieve the tests. :)

I updated the tests taking into account your comments. Let me know if this is more in line with what you described.

Daniel.

**Comment by ccanepa** [comment]
Yes, fine.

A simple additional change: delete from the docstring "It also avoid memory leaks, where
	    reference to old scene is kept as a parent scene."
Then it can be merged.

Why ?
Thats because  CocosNode.parent does not store 'the parent node'; it stores a WeakRef to 'the parent node' so it does not contribute to the object reference count, so does not block GC. (That's why in the test we cannot directly do `new_scene.parent = NotNone()`,  we need the variable not_None_value to have a real reference: else the  WeakRef in .parent decays to None and the test **pass** with the old, incorrect code)

**Comment by dangillet** [comment]
Hi Claudio,

Wow! You made me discover that the `parent` attribute was actually a property using weakref ! I missed that code. This means that there was no memory leak to start with ! When there is a transition, our current scene parent attribute holds a weakref to the *envelope* scene from the TransitionScene. So theoretically the Transition Scene could be garbage collected.

So is this fix really needed ? Do we want to enforce this rule that the current scene should not have any parent ?

Daniel.

**Comment by ccanepa** [comment]
Yes, we still want CocosNode.get_ancestor() and CocosNode.parent to not escape from the active scene.

If the user retains a reference to the outgoing scene, the weakref does not decays.

**Comment by dangillet** [comment]
Ok. I've squashed my commits. Let me know if this is now ok to merge in master.

Thanks for your guidance !

**Comment by ccanepa** [comment]
well... :)
the changelog needs adjustment.
maybe "fix active scene not always the top node in the scenegraph, #254" ?
fix, merge and  close please.

**Comment by ccanepa** [comment]
thanks
