### ISSUE TITLE
PygletRichLabel uses halign

### ISSUE THREAD

**Issue by dangillet** [los-cocos/cocos#258]
Hello,

I found a bug in `cocos.text.PygletRichLabel`. One of the keyword argument used is `halign`. But Pyglet made a change years ago:
```
changeset:   2591:aa3b2412feed
user:        Phillip Nguyen <evil.phillip@gmail.com>
date:        Sun May 22 21:38:24 2011 -0500
files:       pyglet/text/__init__.py
description:
Renamed Label parameter 'halign' to 'align'.  Fix for issue 460.
```

So I propose in the branch `Label` a fix. CHANGELOG updated. Claudio, let me know if ok to merge into master.

Regards,
Daniel.

**Comment by dangillet** [comment]
Claudio, are you ok with these changes ?

Thanks,
Daniel.

**Comment by ccanepa** [comment]
They look ok, merge

**Comment by dangillet** [comment]
So I've deleted the remote branch Label, rebased my commit on master and pushed the change.

Issue closed.
