### ISSUE TITLE
changes in pyglet.sprite.Sprite properties break cocos Sprites

### ISSUE THREAD

**Issue by ccanepa** [los-cocos/cocos#260]
```
Traceback (most recent call last):
  File "test_menu_items.py", line 74, in <module>
    main()
  File "test_menu_items.py", line 71, in main
    director.run( Scene( MainMenu() ) )
  File "test_menu_items.py", line 42, in __init__
    self.create_menu( [item1,item2,item3,item4,item5,item6] )
  File "..\cocos\menu.py", line 294, in create_menu
    self._build_items(layout_strategy)
  File "..\cocos\menu.py", line 230, in _build_items
    layout_strategy(self)
  File "..\cocos\menu.py", line 122, in verticalMenuLayout
    menu.font_item_selected)
  File "..\cocos\menu.py", line 536, in generateWidgets
    color=font_item['color'][:3])
  File "..\cocos\sprite.py", line 155, in __init__
    self.rotation = rotation
  File "..\cocos\cocosnode.py", line 432, in <lambda>
    rotation = property(_get_rotation, lambda self, angle: self._set_rotation(an
gle))
  File "..\cocos\sprite.py", line 205, in _set_rotation
    pyglet.sprite.Sprite._set_rotation(self, a)
AttributeError: type object 'Sprite' has no attribute '_set_rotation'
```

with pyglet changeset 060f5aada runs normal, with  next changeset ( 1dfacd0 ) produces the traceback

The current pyglet on pypi ( 1.2.4 ) works normal.

**Comment by dangillet** [comment]
Hello Claudio,

I might have a way to fix this. I made up some dummy code to show how I extend the setter property to call both base classes setters.

```python
class PygletSprite(object):
    @property
    def rotation(self):
        print("In Pyglet Sprite rotation getter")
        return self._rotation
    
    @rotation.setter
    def rotation(self, rot):
        print("In Pyglet Sprite rotation setter")
        self._rotation = rot

class BatchableNode(object):
    @property
    def rotation(self):
        print("In BatchableNode rotation getter")
        return self._rotation
    
    @rotation.setter
    def rotation(self, rot):
        print("In BatchableNode rotation setter")
        self._rotation = rot

class Sprite(BatchableNode, PygletSprite):
    # We only override the setter `rotation` calling both
    # the BatchableNode setter and Pyglet Sprite setter.
    @BatchableNode.rotation.setter
    def rotation(self, rot):
        super(Sprite, Sprite).rotation.__set__(self, rot)
        PygletSprite.rotation.__set__(self, rot)

s = Sprite()
s.rotation = 3
print(s.rotation)
```

As you can see, setting a value to the `rotation` property calls *both* setter implementations from the base classes. When we access the `rotation` property (so the getter method), we use by default `BatchableNode` getter. We could have chosen the other way around. But both base classes just return the value anyway, so it doesn't matter which one is called.

Let me know what you think, and if you'd like me to go ahead and fix all the `cocos.sprite.Sprite` properties.

Daniel.

**Comment by ccanepa** [comment]
Yes, probably is what we want to do. But let consider this:

We want released cocos work with released pyglet.
Current pyglet in pypi does not use @property
Changing cocos Sprites to support both pyglet 1.2.x and 1.3 would be a pain, so only one version will be supported.
If we release before pyglet 1.3, it would be better to talk to the older style properties.

I posted to pyglet ML to get some hint about their release plan; if near we can start our own refactor, if not probably we can wait some time. 

When doing the properties refactor in cocos, comparison betwwen pyglet Sprite performance and cocos Sprite perf should be done: at some point in time we have a problem due to properties calling two times a heavy method [1] 

[1] http://progcc-en.blogspot.com.ar/2010/11/sprite-performance-in-cocos-and-pyglet.html and follow-up

**Comment by dangillet** [comment]
Hello,

For the first point the good news is that the decorator property syntax is only *syntactic sugar* for what you call the *older style properties*. In my example above, replace only `BatchableNode` by this

```python
class BatchableNode(object):
    def _get_rotation(self):
        print("In BatchableNode rotation getter")
        return self._rotation

    def _set_rotation(self, rot):
        print("In BatchableNode rotation setter")
        self._rotation = rot

    rotation = property(_get_rotation, _set_rotation)
```

and you'll see that it still works with the rest of the code. \o/

For the performance aspect, this is a very good point. But this is already what we currently have. So I don't think that this refactor would make make the code significantly slower. Of course, only real profiling will tell. My humble suggestion would be to *fix* the problem you posted by refactoring the code, and we open a new ticket *enhancement* where we try to improve cocos Sprite class performance.

Daniel.

**Comment by ccanepa** [comment]
fine, do a branch and try it if you want.

**Comment by dangillet** [comment]
Hello,

I made a new branch and made the changes as discussed. Let me know what you think. I tried with pyglet 1.2 and with the new version using the decorators. On my side, I didn't find any problems.

**Comment by ccanepa** [comment]
test_all_collisions.py shows bad positions with pyglet 1.2.4 from pypi.
Currently testing some more scripts from test/

**Comment by ccanepa** [comment]
other scripts that show different behavior:
	test_all_collisions.py
	test_anchor_sprites.py
	test_hierarchy.py
	test_hierarchy2.py
	test_scalexy.py
	test_sprite_aabb.py

with the cocos proposed changed the images produced don't match the last released cocos.
verified with both pyglet 1.2.4 and tip of pyglet default branch

**Comment by dangillet** [comment]
Hi Claudio,

Thank you very much for these tests ! They helped me greatly in finding the problem. I found it and pushed the correction on the sprite_properties branch. The tests seem now to work correctly.

**Comment by ccanepa** [comment]
High Five !
I see all normal, and the dual support code looks quite legible.
Kudos for your solution.

Can you squash and commit to master ?

**Comment by dangillet** [comment]
Commits squashed and merge to master. Branch deleted.
