### ISSUE TITLE
Particles custom texture

### ISSUE THREAD

**Issue by dangillet** [los-cocos/cocos#264]
I noticed that due to Issue #235, the fire texture is loaded lazily. But this does not offer the opportunity to clients code to set their own texture. Maybe it would be best to have the texture class attribute contain the file name for the texture, and load it during the __init__ method. Something along the line of
```python
def load_texture(self):
    pic = pyglet.image.load(self.texture, file=pyglet.resource.file(self.texture))
    self.__class__.texture = pic.get_texture()
```
Daniel.

**Comment by dangillet** [comment]
Here is a fix proposal. Let me know if ok to merge.

**Comment by ccanepa** [comment]
In the old code, the canonical way to use a custom texture seems to be by overriding load_texture, albeit is not mentioned in the docstrings.

Putting the texture name in .texture and then replace after first ```__init___``` with the texture object is a bit dirty (at different times the member .texture holds semantically different things); also, by passing name the use of run time generated textures is ruled out.

I wrote an alternative version [ branch https://github.com/los-cocos/cocos/tree/another_particle_texture ]
Same as old version, but
- better docstrings
- now it is possible to specify custom textures on a per-instance basis (additionally to the per-class supported by the old code)

Do you think is clear enough ? Any other feedback ?

**Comment by dangillet** [comment]
Hi Claudio,

This is indeed a much better version. Thanks ! I didn't think about being able to override the `load_texture` method. This is so nice that the user has even the choice between a class default texture, and still can give a per-instance texture.

Well done !

I think it's very clear. I'm currently busy with the new docstrings. But I'll wait till you merge into master, then I'll rebase my own local `documentation` branch on top of this commit and I will amend a few things in the doctstrings. It's certainly not about the text itself, but simple things like how to make the code example look like code. :)

**Comment by ccanepa** [comment]
committed to master at b65bf97caa48614610da3fe328798ee52f221f3e

RE documentation: feel free to change the text.
