### ISSUE TITLE
Obsolete EventHandlerMixin class

### ISSUE THREAD

**Issue by dangillet** [los-cocos/cocos#268]
There is a useless class in the **scene.py** file : `EventHandlerMixin`.
`Scene` inherits from it, but as its second parent in line. So its methods will never be called. In other words, when we call `Scene.add` or `Scene.remove`, we will effectivly call `CocosNode.add` and `CocosNode.remove`, not `EventHandlerMixin.add` nor `EventHandlerMixin.remove`.

I suspect all this is some legacy code. We can see from `EventHandlerMixin` that the original intent was that the `Scene` would call `push_all_handlers` on all `Layer`. But today, the responsability is within the `Layer` to register itself in its `on_enter` method and un-register in its `on_exit` method if it has `is_event_handler=True`.

So should I refactor this code, deleting the `EventHandlerMixin` class ?

Also I think that when a `Scene` enters the stage, its `Layer` will get registered twice with `director.window`. In [director.py L530](https://github.com/los-cocos/cocos/blob/master/cocos/director.py#L530), we call `self.scene.enable_handlers(True)` which seems also to be some legacy method. This method will call `Scene.push_all_handlers()` which in turn will call all children `Layer.push_all_handlers()` methods. This finally calls `director.window.push_handlers(self)`. But then on [Line 531](https://github.com/los-cocos/cocos/blob/master/cocos/director.py#L531) we call `scene.on_enter()` which calls `on_enter()` for all children. `Layer.on_enter()` has this code:
```python
if scn._handlers_enabled:
    if self.is_event_handler:
        director.window.push_handlers(self)
```
So it's a second time we register to `window`. I think that removing the whole mechanism with `Scene.enable_handlers()` would still allow the code to work correctly. What was the intent ? To be able to tell a Scene not to be active anymore ? But in this case, shouldn't we just use `Scene.remove_all_handlers()` ?

**Comment by ccanepa** [comment]
I'm ok with removing EventHandlerMixin.

Some blackbox testing around Layer.push_all_handlers

- intercepting calls to pyglet window.push_all_handlers does not show double calling in a simple scenario. Test script:
```python
class KeyDisplay(cocos.layer.Layer):

    is_event_handler = True

    def on_key_press(self, key, modifiers):
        print(pyglet.window.key.symbol_string(key))
        return None


class KeyNull(cocos.layer.Layer):

    is_event_handler = True

    def on_key_press(self, key, modifiers):
        print('*')
        return None


def make_interceptor(window):
    old_push_handlers = window.push_handlers
    def spy_push_handlers(*args):
        print(*args)
        old_push_handlers(*args)
    return spy_push_handlers
    

if __name__ == "__main__":
    director.init(resizable=True)
    # intercept pyglet.window.push_handlers
    director.window.push_handlers = make_interceptor(director.window)
    # Run a scene with our event displayer
    key_display_layer = KeyDisplay()
    key_null_layer = KeyNull()
    key_display_layer.add(key_null_layer)
    director.run(cocos.scene.Scene(key_display_layer))
```
running and pressing keys 'h' and ESC gives the output:
```
K:\sync2\_working_now\cocos scene events #268>py -3.5 scene_events.py
<__main__.KeyNull object at 0x00000000010F8940>
<__main__.KeyDisplay object at 0x000000000688F828>
H
*
ESCAPE
*
```
Shows one call for each Layer that handles events, so no double registration here.

- Commenting out Layer.push_all_handlers() and running all scripts in test/ fails only in test_transitions_with_pop_recipe.py

We'll see ...

**Comment by dangillet** [comment]
Thanks for these tests.

Indeed there are no duplicate calls because of this if statement in `Scene.enable_handlers`
```python
if value and not self._handlers_enabled and self.is_running:
    self.push_all_handlers()
```
in which `self.is_running` is `False` when it gets called. When `director` calls its `_set_scene` method, there is a call to `enable_handlers(True)` which sole purpose is to set `self._handlers_enabled = True`.

So it does what it should. The problem I see is that `push_all_handlers` and `remove_all_handlers` are both public methods, so to say. And they don't give a damn about the `self._handlers_enabled` attribute. My point is that if the client code mixes calls `remove_all_handlers()` and `enable_handlers(True)`, this is not going to work. This last call will not push all the handlers back because `self._handlers_enabled` is still `True`.

Here is a little example showing the problem
```python
import cocos
from cocos.director import director
from cocos.actions import Delay, CallFunc
import pyglet

class TestLayer(cocos.layer.Layer):

    is_event_handler = True

    def __init__(self, *args, **kwargs):
        super(TestLayer, self). __init__(*args, **kwargs)
        self.enabler_type = 'push_all_handlers'

    def on_key_press(self, key, modifiers):
        if key == pyglet.window.key.D:
            print("Disabling Scene event handlers with remove_all_handlers for 3 seconds.")
            scene = self.get_ancestor(cocos.scene.Scene)
            scene.remove_all_handlers()
            call_me_back = Delay(3) + CallFunc(self.enable_scene_handlers)
            self.do(call_me_back)
        elif key == pyglet.window.key.C:
            self.enabler_type = 'enable_handlers' if self.enabler_type == 'push_all_handlers' else 'push_all_handlers'
            print("Changing the way Scene event handlers are enabled with", self.enabler_type)
        else:
            print(pyglet.window.key.symbol_string(key))

    def enable_scene_handlers(self):
        print("Enabling Scene event handlers with", self.enabler_type)
        scene = self.get_ancestor(cocos.scene.Scene)
        enabler_fn = getattr(scene, self.enabler_type)
        enabler_fn()



if __name__ == "__main__":
    director.init(resizable=True)
    test_layer = TestLayer()
    print("Pressing D will disable the Scene event handlers for 3 seconds. "
        "In that interval, pressing any key won't have any effet.")
    print("Pressing C will change the way the Scene event handlers are re-enabled. "
        "By default we use push_all_handlers. But if we mix remove_all_handlers with "
        "enable_handlers then we see that we never receive any key presses.")
    director.run(cocos.scene.Scene(test_layer))
```

**Comment by dangillet** [comment]
I removed the `EventHandlerMixin` class and pushed the changes in [scene_cleanup](https://github.com/los-cocos/cocos/tree/scene_cleanup) branch.

I will open new issues for the other problems I notices, like the `enable_handlers` method.

**Comment by dangillet** [comment]
Issue closed.
