### ISSUE TITLE
Scene push_all_handlers and remove_all_handlers problems

### ISSUE THREAD

**Issue by dangillet** [los-cocos/cocos#269]
`Scene` class has two different ways to push or remove all events handlers in the scene.

1. Using `push_all_handlers()` and `remove_all_handlers()`
2. Using `enable_handlers(True)` and `enable_handlers(False)`

The problem is that if the client code mixes calls from these two categories, the methods might not do what is expected.

Here is a sample program showing the problem.
```python
import cocos
from cocos.director import director
from cocos.actions import Delay, CallFunc
import pyglet

class TestLayer(cocos.layer.Layer):

    is_event_handler = True

    def __init__(self, *args, **kwargs):
        super(TestLayer, self). __init__(*args, **kwargs)
        self.enabler_type = 'push_all_handlers'

    def on_key_press(self, key, modifiers):
        if key == pyglet.window.key.D:
            print("Disabling Scene event handlers with remove_all_handlers for 3 seconds.")
            scene = self.get_ancestor(cocos.scene.Scene)
            scene.remove_all_handlers()
            call_me_back = Delay(3) + CallFunc(self.enable_scene_handlers)
            self.do(call_me_back)
        elif key == pyglet.window.key.C:
            self.enabler_type = 'enable_handlers' if self.enabler_type == 'push_all_handlers' else 'push_all_handlers'
            print("Changing the way Scene event handlers are enabled with", self.enabler_type)
        else:
            print(pyglet.window.key.symbol_string(key))

    def enable_scene_handlers(self):
        print("Enabling Scene event handlers with", self.enabler_type)
        scene = self.get_ancestor(cocos.scene.Scene)
        enabler_fn = getattr(scene, self.enabler_type)
        enabler_fn()



if __name__ == "__main__":
    director.init(resizable=True)
    test_layer = TestLayer()
    print("Pressing D will disable the Scene event handlers for 3 seconds. "
        "In that interval, pressing any key won't have any effet.")
    print("Pressing C will change the way the Scene event handlers are re-enabled. "
        "By default we use push_all_handlers. But if we mix remove_all_handlers with "
        "enable_handlers then we see that we never receive any key presses.")
    director.run(cocos.scene.Scene(test_layer))
```

A possible solution is to add to the documentation a warning in `push_all_handlers` and `remove_all_handlers` that these methods were not meant to be part of the public interface. In future releases of cocos2D, they will be renamed `_push_all_handlers` and `_remove_all_handlers`.

It seems that the purpose of `enable_handlers` is to safeguard an application from calling `push_all_handlers` if the scene is not active, ie. `self.is_running = False`. So this is probably a good thing. Calling `push_all_handlers` bypasses those checks and could lead to subtle bugs.

As a convenience to the user, I would personally add an alias to `enable_handlers(False)` named `disable_handlers()`.

Daniel.

**Comment by ccanepa** [comment]
Looking at the code I think there are two parallel systems to handle registration of pyglet window events:

1. Embedded in on_enter / on_exit. It uses
	scene._handlers_enabled : bool controlled by Scene.enable_handlers()
	Layer.on_enter : register if ancestor(Scene)._handlers_enabled == True
	Layer.on_exit : de-registers if ancestor(Scene)._handlers_enabled == True
   Scene event handlers aren't pushed in Scene.on_enter

   Invoked
     - indirectly by director when it changes the active scene (sets the _handlers_enabled, calls scene.on_enter)
     - by CocosNode add / remove methods, which calls on_enter / on_exit

2. dedicated methods in Scene and Layer, uses
	Scene.enable_handlers() : sets / resets _enable_handlers, calls Scene.push_all_handlers
        Scene.remove_all_handlers (checks .is_running and _enable_handlers
	Scene.push_all_handlers: calls push_all_handlers on all child Layers (no conditionals)
	Layer.push_all_handlers : if Layer.is_event_handler registers its own handlers. Additionally, propagates to child Layers; does not check other flags to allow / disallow registering
	Layer.pop_all_handlers : if Layer.is_event_handler de-registers its own handlers. Additionally, propagates to child layers

Probably the second system would have been collaborating with the now eliminated EventHandlerMixin

Functional differences:

- System1 needs to perform an on_enter / on_exit to allow a push / remove, System 2 is independent of on_enter / on_exit. The only vaguely plausible use case for system2 for this seems to be an entity that wants to disable user input but still be in the scene, and it can be implemented with a flag an and 'if' in the entity event handlers.

- System2 bloats the api, and the extra calls are not safe to call at all times, so warnings and docs.

I lean to simplicity, so I would favor
    - eliminate system2
    - system1 stays with a little modification:
          - director handles itself the switching of scene._handlers_enabled
          - method Scene.enable_handlers disappears (under System1 only switched scene._handlers_enabled )

This works, it is simple, and doesn't expose tricky methods in Scene.
Running the scripts in test/ they are no tracebacks.

Made these changes in a branch on top of your branch, https://github.com/los-cocos/cocos/tree/scene_cleanup_more

What do you think ?

**Comment by dangillet** [comment]
I agree with everything. I'm even pushing a tiny bit further. Why do we need `Scene._handlers_enabled` ?

It seems to me that this flag is part of system 2. 

So I merged your changes to my branch. I pushed a new commit where I've deleted all references to `Scene._handlers_enabled` and all tests seem to pass. Do you think it's safe like this ?

Note: The programming guide will need to be updated as well. I could find mentions of `Scene.enable_handlers` in those pages:
- http://python.cocos2d.org/doc/programming_guide/basic_concepts.html?highlight=enable_handler#cocos-and-events
- http://python.cocos2d.org/doc/programming_guide/transitions.html?highlight=enable_handler

Daniel.

**Comment by ccanepa** [comment]
re: removing Scene._handlers_enabled
I'm ok with removing the references in on_enter / on_exit .
Still, I would left the flag and asserts in director.py :
- when someone implements a variation on scene sequencing, it warns about double registration or double free bugs
- it nicely informs the reader that current code expects an scene 'to be cold' to enter the stage and 'to be hot' to exit the stage.

Good catch with the doc mentions. Would you correct them ?

**Comment by dangillet** [comment]
Indeed, this is *defensive programming*. I think you are absolutely correct. Better to catch this problem earlier.

So I made the necessary changes. I also amended the programming guide (and fixed a couple of links).

Let me know if it's ok to squash and merge to master.

**Comment by ccanepa** [comment]
yes, it is ready to merge and close. Nice work.

You may consider to squash as two commits
- all but the last
- the last

so that it is easier to spot the functional changes in a diff, if a user / dev want to look at that

Congrats.

**Comment by dangillet** [comment]
Issue closed.

Thanks for the inputs !

**Comment by ccanepa** [comment]
removed three remaining uses of Scene.enable_handlers()
