### ISSUE TITLE
preparing 0.6.4 release

### ISSUE THREAD

**Issue by ccanepa** [los-cocos/cocos#270]
Created branch https://github.com/los-cocos/cocos/tree/toward_release_0.6.4

Done
- CHANGELOG and NEWS updated
- added compatibility notes in the docs
- updated programming guide re: map colliders
- docs: eliminated promise 'front to back event propagation'  (never fulfilled)
- simplified platformer-map.xml / platformer-tiles.xml to reflect simplified RectMapCollider  (no props)
- docs: editor.py warn to not inline tilesets
- see that programming guide is updated to reflect changes mentioned in changelog
- continue with the tasks in tools/release_checklist_template.txt: -> pypi upload, git tagging done
- edited cocos site master (https://github.com/los-cocos/cocos-site) , asked upstream to update. 

TODO
- wait for python.cocos2d.org pull from master (usually one or two days), then announce at pyglet, cocos and pyar mail list.

@dangillet : feel free to branch my branch to propose better wording

**Comment by dangillet** [comment]
Hello Claudio,

I was very impressed by all the work you have been doing on the documentation. Well done !

I have reviewed what was changed and I edited a few things. I also tried to add as many link as possible to the API documentation. I feel that it's more user friendly for a newcomer to be able to navigate from the Programming Guide directly to the API documentation to check out something and then go back, rather than try to find where the class or method is documented.

There is still something bothering me a little. We have noticed that the tile editor is not really functional in terms of saving changes back to XML. Should we at least add a note in the documentation ? I could try to look at a fix, but I doubt it would be possible to fix it before you release 0.6.4.

I will now have a look at platformer-map.xml / platformer-tiles.xml to reflect simplified RectMapCollider ? (no props).

**Comment by dangillet** [comment]
I removed the pros from platformer-tiles.xml and everything seems to work correctly.

**Comment by ccanepa** [comment]
thanks, merged all to master.

> There is still something bothering me a little. We have noticed that the tile editor is not really functional in terms of saving changes back to XML. Should we at least add a note in the documentation ? I could try to look at a fix, but I doubt it would be possible to fix it before you release 0.6.4.

Will add a note now. Re modifications:I would let it alone until release its done, no last moment code changes.

**Comment by ccanepa** [comment]
note added on master.

**Comment by ccanepa** [comment]
v0.6.4 uploaded to pypi.

remains update cocos site & anounce

**Comment by dangillet** [comment]
Well done !

Where do you normally announce this ? Can I help with something ?

**Comment by ccanepa** [comment]
Current status in the OP.

>Where do you normally announce this ?

english: pyglet ML, cocos-discuss ML ; spanish: pyar ML

> Can I help with something ?

Well, all it remains is to redact the announce. I usually do by basically using the 'news' announce in the site.

But, if you want, you can try: 
 + If you want to rephrase, go for it (but don't over-promise).
 + If you know other ML / forums where the announce will be not off-topic, propose them.
 + If some  of those sites talk other than spanish or english, do a translated version.

**Comment by dangillet** [comment]
Following the guidelines of the previous announcement you made for v 0.6.3, here is what it would look like for the new version:

Hello everyone,

The latest version of Cocos2d for Python has been released ! 
Besides small bugfixes, this release brings:

- MapColliders classes changed API to be more useful and clear: collision between actors and tiles and between actors and TmxObject are easier to handle.
- Supports the variants 'csv', 'xml', 'base64(uncompressed)' for Tiled Editor layer data.
- Simpler Scene and Layer code for automatic window events registration.
- Particle systems now accepts per-instance texture.
- Better IDEs autocompletion: by being more specific in cocos code imports, IDEs can work faster and be more selective with the autocompletion offerings.
- Support for pyglet 1.3.

Be sure to read about compatibility changes in the docs, there has been some api changes.
  
Full Changelog at https://raw.githubusercontent.com/los-cocos/cocos/master/CHANGELOG

Available from pypi https://pypi.python.org/pypi/cocos2d/0.6.4
or github https://github.com/los-cocos/cocos


What is cocos2d:
A framework for building 2D games, demos, and other graphical/interactive applications.
Draws using OpenGL, which is hardware accelerated.
Targets the Operating Systems Linux, Mac or Windows on PC-like hardware.
Provides some conventions and classes to help you structure a "scene based application".
A cocos2d application consists of several scenes, and a workflow connecting the different scenes.
It provides you with a "director" (a singleton) which handles that workflow between scenes.
Each scene is composed of an arbitrary number of layers; layers take care of drawing to the screen (using the pyglet and OpenGL APIs), handling events and in general contain all of the game/application logic.

cocos2d simplifies the game development in these areas:

* Flow control: Manage the flow control between different scenes in an easy way
* Sprites: Fast and easy sprites
* Actions: Just tell sprites what you want them to do. Composable actions like move, rotate, scale and much more
* Effects: Effects like waves, twirl, lens and much more
* Tiled Maps: Support for rectangular and hexagonal tiled maps
* Collision: Basic pure python support for collisions
* Transitions: Move from scene to scene with style
* Menus: Built in classes to create menus
* Text Rendering: Label and HTMLLabel with action support
* Built-in Python Interpreter: For debugging purposes
* Access to OpenGL functionality
* and much more! http://python.cocos2d.org

Enjoy !

----------------

I was just wondering if it would be a good idea to say that we are looking for volunteers to help make cocos2d better ? Or you prefer to keep it *quiet* as it's not your main project anymore.

For other sites / forums, I could think of:
http://www.gamedev.net/index
http://www.dreamincode.net/forums/

I could translate the announcement in french and would suggest to post it on the following forums (in the relevant section):
http://www.developpez.com/
https://openclassrooms.com/forum/

Let me know what you think.

**Comment by harbdog** [comment]
Out of curiosity, why aren't the Primitives tools included in the distro? I just happened upon them while looking up how to make simple shapes in cocos and saw the file in tools in source here but not in the distro installed with pip.
