### ISSUE TITLE
TMX loading is broken (with fix)

### ISSUE THREAD

**Issue by FluffyInkie** [los-cocos/cocos#272]
Texture clamping for TMX tilesets does not work and raises an OpenGL exception in some situations.
In tiles.py, in from_atlas, line 634:
`gl.glBindTexture(tile_image.texture.target, id)`
should be:
`gl.glBindTexture(tile_image.texture.target, tile_image.texture.id)`

**Comment by ccanepa** [comment]
You are right. Thanks for the report and patch. Committed to master.
