### ISSUE TITLE
Transitioning from one Menu scene to another loses handlers

### ISSUE THREAD

**Issue by harbdog** [los-cocos/cocos#273]
I'm trying to have each menu screen be its own class, self contained, but the problem is that when I have the director swap/push to the next menu screen scene (with or without an actual animated transition), I get the new menu scene but no ability to interact with the actual menu items.

Reproduction:

`class MainMenu(Menu):` contains a Settings menu item, that when acted on does the following:

    def on_settings(self):
        print("Settings...")
        scene = cocos.scene.Scene()
        scene.add(settings.SettingsMenu())
        director.push(FlipX3DTransition(scene, duration=0.5))

The `SettingsMenu `is another simple Menu classed thing with a couple of its own menu items and a return item that calls `self.on_quit` to do `director.pop()` to go back to the main menu. The only problem is that once the settings menu is entered, I can see the new settings menu just fine, but clicking and pressing keyboard keys does nothing. Only the escape key does anything, which just pops back to showing the MainMenu (though doesn't appear to do so by invoking the SettingsMenu's `on_quit`).

Any idea how to workaround this, since according to the doc `director.push` is supposed to handle transfer of handlers?

**Comment by ccanepa** [comment]
Maybe the problem is in some code you don't show ?

Attached is an example with main menu in one scene, submenu in another; it
works as supposed both with mouse and KBD
(except for this, which I think is a defect: on entering a menu or submenu,
if the mouse cursor happens to be over an item, the item is not highlighted
and a click does nothing; after moving over any other item one time, the
mouse will interact normally with any item.)
Does it work for you ?

As a side note, another way to handle submenues is using a MultiplexLayer;
in the test\ directory theres a relevant sample ( test_multiplex_layer.py )

**Comment by ccanepa** [comment]
oh, I assumed it was from the mailing list. Well, pasted below the code

```python
from __future__ import division, print_function, unicode_literals


import pyglet
from pyglet import font

from cocos.director import director
from cocos.menu import *
from cocos.scene import Scene
from cocos.actions import Rotate

class MainMenu(Menu):
    def __init__( self ):
        super( MainMenu, self ).__init__("Main Memu" )

        self.menu_valign = TOP
        self.menu_halign = LEFT

        # then add the items
        items = [
            ( MenuItem('Submenu 1', self.on_submenu ) ),
            ( MenuItem('Quit', self.on_quit ) ),

        ]

        self.create_menu( items, selected_effect=zoom_in(),
                          unselected_effect=zoom_out())


    def on_submenu(self):
        print('on_submenu')
        director.push(Scene(Submenu()))

    def on_quit( self ):
        pyglet.app.exit()

class Submenu(Menu):
    def __init__( self ):
        super( Submenu, self ).__init__("SubMemu" )

        self.menu_valign = TOP
        self.menu_halign = LEFT

        # then add the items
        items = [
            ( MenuItem('Rotate', self.on_rotate ) ),
            ( MenuItem('Back',  self.on_quit) ),

        ]

        self.create_menu( items, selected_effect=zoom_in(),
                          unselected_effect=zoom_out())

    def on_rotate(self):
        director.scene.do(Rotate(360, 1.0))

    # by default a menu calls aelf.on_quit when it sees the key 'ESC',  so
    # we define it; additionally we routr here clicks on the 'Back' item
    def on_quit(self):
        director.pop()

def main():

    director.init( resizable=True)
    director.run( Scene( MainMenu() ) )

if __name__ == '__main__':
    main()
```

**Comment by harbdog** [comment]
Thanks for the example! It led me to figure out what the real difference was between what I had and what I saw there that worked. Eventually figured out that I had created an `on_enter ` def for my SettingsMenu, which apparently gets in the way of the handoff of handlers. Removing `on_enter `fixed the problem!
