### ISSUE TITLE
Cannot pass keyword args to pyglet.Sprite

### ISSUE THREAD

**Issue by dangillet** [los-cocos/cocos#274]
I wanted to create a `cocos.Sprite` with a different blending than normal. `pyglet.Sprite` has in its signature 
```python
    def __init__(self,
                 img, x=0, y=0,
                 blend_src=GL_SRC_ALPHA,
                 blend_dest=GL_ONE_MINUS_SRC_ALPHA,
                 batch=None,
                 group=None,
                 usage='dynamic',
                 subpixel=False):
```

But there is no way to pass this keyword arguments from the `cocos.Sprite` class.

**Comment by ccanepa** [comment]
Code looks good.
Changelog needs to be rebased on master
Use a more descriptive commit text (usually the line added to changelog plus ", #issue_number" is a good commit message)

**Comment by dangillet** [comment]
Fix merged and CHANGELOG updated.
