### ISSUE TITLE
HMTLLabel does not show img

### ISSUE THREAD

**Issue by dangillet** [los-cocos/cocos#276]
When using an `HTMLLabel`, the images are not displayed at all. I tried to make a demo code in the [etc_code](https://github.com/los-cocos/etc_code) repo, but it seems I don't have the required privilege to do it.

Anyway, the demo is super simple. Place the following code with the `grossini.png` image found in `cocos\samples` in a folder, and you'll see the problem.

```python
#!/usr/bin/env python3
# -*-coding:utf-8 -*

import cocos
from cocos.text import HTMLLabel
from cocos.director import director

class TestLayer(cocos.layer.Layer):
    def __init__(self):
        super(TestLayer, self).__init__()

        x, y = director.get_window_size()

        self.text = HTMLLabel("""<center><font color=white size=4>
Image here --><img src="grossini.png"><-- here.</font></center>""", 
            (100, y//2))
        self.add(self.text)

def main():
    director.init()
    test_layer = TestLayer()
    main_scene = cocos.scene.Scene(test_layer)
    director.run(main_scene)

if __name__ == '__main__':
    main()
```

Dan.

**Comment by ccanepa** [comment]
> I tried to make a demo code in the etc_code repo, but it seems I don't have the required privilege to do it.

I see you as having write access to all projects in los-cocos, which includes etc_code:
[pics](http://imgur.com/a/Vzrs8)

Pics taken today, but I changed nothing from the time I initially added you.

Maybe you can checkout etc_code, add a "hello" at the end of readme and commit and push to see how it goes ? And post here any error message if any ?

**Comment by dangillet** [comment]
Fix rebased onto master and CHANGELOG updated accordingly.

**Comment by dangillet** [comment]
>  see you as having write access to all projects in los-cocos, which includes etc_code

I noticed that I had the HTTPS url. I changed it now to SSH and it works correctly. I pushed a new commit with a little test showing the problem.

Daniel.
