### ISSUE TITLE
CollisionManager methods should throw NotImplementedError

### ISSUE THREAD

**Issue by Fedor-Lyanguzov** [los-cocos/cocos#290]
Good day.

Should methods of CollisionManager interface throw NotImplementedError instead of just passing? It seams reasonable, since none of subclasses use super(), and since CollisionManager is interface (or abstract class).

I can make changes myself, write little tests and make pull request, but i'm very bad with `git rebase` and i don't know how to run tests :sob: . 

Fedor

**Comment by ccanepa** [comment]
Hi

Probably it would be better to make the interfaces Abstract Base Class es (ABCs) and add @abstractmethod to the methods

**Comment by ccanepa** [comment]
But differences in py2-3 metaclass declaration will make a p2-3 compatible declaration unnecessarily hard to read. 

Added the label 'pure py3' to revisit the issue when py2 support will be dropped, closed till that moment

**Comment by Fedor-Lyanguzov** [comment]
Here is my reasoning:

> Errors should never pass silently.
> Unless explicitly silenced.
> -- Zen of Python, by Tim Peters

Right now we have errors, that pass silently - when someone is programming collisions, it's easy to forget about the nature of CollisionManager, and there is no explicit warning at runtime.

>exception NotImplementedError
>This exception is derived from RuntimeError. In user defined base classes, abstract methods should raise this exception when they require derived classes to override the method.
> -- [Python 2 docs](https://docs.python.org/2/library/exceptions.html#exceptions.NotImplementedError)

>exception NotImplementedError
>This exception is derived from RuntimeError. In user defined base classes, abstract methods should raise this exception when they require derived classes to override the method, or while the class is being developed to indicate that the real implementation still needs to be added.
> -- [Python 3 docs](https://docs.python.org/3/library/exceptions.html#NotImplementedError)

Raising NotImplementedError is a way to solve the problem. It is compatible with Python 2 and Python 3 at the same time. It is short. It does not need hard-to-understand metaclass declarations.

By the way, when you plan to drop Python 2 compatibility?

**Comment by dangillet** [comment]
Hi Claudio,

AbstractBaseClass is the superior solution. But as you said, it would make the code ugly to support Python 2.

As @Fedor-Lyanguzov said, using just a `raise NotImplementedError` could be a nice way to enforce the idea that those methods need to be implemented. What do you think?

Dan

**Comment by ccanepa** [comment]
**re abc:** Ok, ok, will do the raise NotImplementedError

**re when to drop py2 support**: at most at py2 official end of life, 2020, but realistically anytime when a nontrivial feature produces ugly compatibility code.
Warnings will be issued one release before drop.

**Comment by ccanepa** [comment]
done
