### ISSUE TITLE
Changing the resize algorithm for pixel-perfect scaling?

### ISSUE THREAD

**Issue by bweir** [los-cocos/cocos#298]
Hi there,

I'm interested in making a retro-style game with a very low in-game resolution (like 320x240), but resizing the game surface to a large window size results in a blurry image. Does cocos expose a function for setting a different scaling algorithm? Is there a way to hack this functionality? Like through pyglet directly?

Anyways, thank you for your help in advance!

**Comment by ccanepa** [comment]
No direct support in cocos or pyglet, but search for 'pixelated' in the
cocos and pyglet google groups; some relevant results are

cocos
https://groups.google.com/d/msg/cocos-discuss/y0xgTm2Ix_E/LrSdwpvS2ZQJ

pyglet
https://groups.google.com/d/msg/pyglet-users/B7Sbx7wGtZ0/IkvKyoLR77wJ
https://groups.google.com/d/msg/pyglet-users/s8Icda9oPnY/vL6QsRa_Q7gJ

**Comment by bweir** [comment]
Ah, excellent, thank you so much! This is just what I was looking for. I'm building in a virtual environment, so patching pyglet is no big deal.

Though, this leads to another question. Is there a way to scale a scene programmatically, such that the window resizes? I tried creating a scene that was a child of another scene, and scaling it when adding to the parent, but that seems to rather create a zoom effect, chopping the edges of a TMX map, for example.

My first guess would be that director.init would need a parameter to set an arbitrary scale factor on initialization. Actually, there doesn't seem to be any way to set the resolution of a scene separate from the window size in general. Is there a way to accomplish either of these things? Hacks or otherwise?

**Comment by ccanepa** [comment]
On Sun, Aug 20, 2017 at 8:05 AM, Brett Weir <notifications@github.com>
wrote:

> Ah, excellent, thank you so much! This is just what I was looking for. I'm
> building in a virtual environment, so patching pyglet is no big deal.
>
> Though, this leads to another question. Is there a way to scale a scene
> programmatically, such that the window resizes?
>

Scaling a scene changes the zoom factor and never the window size.
If you want to resize the window, well, you resize the window, like
    director.window.set_size(600, 600)

does this help ?

**Comment by ccanepa** [comment]
And, the autoscale param you pass in director.init influences if the window
resize will do a scene resize to show same content as before the window
resize or no scene resize and will show more or less world area. If you
want to show the same world area, autoscale must be True, which is the
default.

**Comment by bweir** [comment]
Ahh, that is exactly what I was looking for! Here's what I did:

    director.init(width=160,
                  height=120,
                  autoscale=True,
                  resizable=False,
                  caption='Game test!')
    director.window.set_size(640, 480)

Here's what the result looks like:

![game test _002](https://user-images.githubusercontent.com/9509912/29503861-3c802154-85f0-11e7-8f1c-e56a01e30c6e.png)

I'm more used to working with low-level blitting operations, so I still have a lot to learn about this library. Would it be accurate to say that Cocos2D is 2D implemented on top of 3D?

Anyway, thanks for your help!

**Comment by ccanepa** [comment]
Nice.
Yes, Cocos2D is 2D implemented on top of 3D. It could even mix a bit of 3D
into a 2D scene, as this pyweek entry shows
https://code.google.com/archive/p/aiamsori/
