### ISSUE TITLE
KeyError in CollisionManagerGrid.objs_near

### ISSUE THREAD

**Issue by Intey** [los-cocos/cocos#300]
I catch `KeyError` when iterate over objects from `objs_near` from `CollisionManagerGrid`.
https://github.com/los-cocos/cocos/blob/151a6629cd5237a2b0694e30f5653aef17022b84/cocos/collision_model.py#L784

Error appears when i pass to ScrollableLayer  width and height that less than map width and height. 
A can make PR with fix and provide more info, if need.

**Comment by ccanepa** [comment]
Thanks for the report.

Indeed CollisionManagerGrid.objs_near raises a KeyError when calling with an object that is not a known object.

This is a bug, and I fixed at commit cdc692c

**Comment by ccanepa** [comment]
Renamed the issue to 'KeyError in CollisionManagerGrid.objs_near' and closed.

If some other error appears, please open other issue.

**Comment by Intey** [comment]
Thanks!
