### ISSUE TITLE
cocos.draw.Circle (and Line) not working on Python 

### ISSUE THREAD

**Issue by rogeriodec** [los-cocos/cocos#315]
Trying to run this code: 

```
import cocos
class Ant(cocos.layer.Layer):
    def __init__(self):
        super(Ant, self).__init__()
        centerPoint=cocos.draw.Vector2(200,200)
        circle=cocos.draw.Circle(centerPoint, 30.0)
        self.add(circle)

cocos.director.director.init(width=640, height=480)
scene=cocos.scene.Scene(Ant())
cocos.director.director.run(scene)
```

I get these errors: 

> Traceback (most recent call last):
>   File "C:/Users/Rogerio/Desktop/Python/PyCharm/carro/teste2.py", line 11, in <module>
>     cocos.director.director.run(scene)
>   File "C:\Program Files\Python\lib\site-packages\cocos\director.py", line 403, in run
>     self._set_scene(scene)
>   File "C:\Program Files\Python\lib\site-packages\cocos\director.py", line 532, in _set_scene
>     scene.on_enter()
>   File "C:\Program Files\Python\lib\site-packages\cocos\scene.py", line 89, in on_enter
>     super(Scene, self).on_enter()
>   File "C:\Program Files\Python\lib\site-packages\cocos\cocosnode.py", line 611, in on_enter
>     c.on_enter()
>   File "C:\Program Files\Python\lib\site-packages\cocos\layer\base_layers.py", line 73, in on_enter
>     super(Layer, self).on_enter()
>   File "C:\Program Files\Python\lib\site-packages\cocos\cocosnode.py", line 611, in on_enter
>     c.on_enter()
> AttributeError: 'Circle' object has no attribute 'on_enter'
> 

How to solve this?

**Comment by ccanepa** [comment]
cocos.draw only supports to draw lines.

The Circle class that appears in draw comes from an
  from cocos.euclid import *
in the cocos.draw module, and
    - it only provides some geometricas calculations
    - is not a CocosNode

Most of the time a Sprite with apropiate picture will do.

**Comment by rogeriodec** [comment]
![2018-09-25_142755](https://user-images.githubusercontent.com/11199752/46031455-44cf4e00-c0cf-11e8-8817-5fe91c4fe8e8.png)

Ok, but with this code, I get a random dotted line, why? 

# This code is so you can run the samples without installing the package
import sys
# import os

# sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
#

# testinfo = "s, q"
# tags = "Draw, Line"

```
import cocos
from cocos.director import director
from cocos import draw


class TestLayer(cocos.layer.Layer):
    def __init__(self):
        super().__init__()
        line = draw.Line((0, 0), (550, 450), (255, 255, 255, 255))
        self.add(line)


def main():
    director.init()
    test_layer = TestLayer()
    main_scene = cocos.scene.Scene(test_layer)
    director.run(main_scene)


if __name__ == '__main__':
    main()

```

**Comment by ccanepa** [comment]
Of the top of my head I would guess that Line's default stroke_width=1
creates lots of very small geometry that is discarded by the openGL driver.

**Comment by rogeriodec** [comment]
In fact, very buggy. Useless function. It just creates a solid line with stroke_width > 2. But I need a width = 1.
