### ISSUE TITLE
release cocos 2019

### ISSUE THREAD

**Issue by ccanepa** [los-cocos/cocos#320]
@r1chardj0n3s started the work to next cocos release with PR #319 and by mail we settled on a basic plan 

 - wait for pyglet to release1.4.2, because cocos #317;  Richard asked Benjamin on Discord, and it will be near Monday (2019 08 12 ?)

- give me a few days to run some semiautomatic tests to see if some more needs fixes

- try to fix whatever looks important

- Richard is the release manager this time  

Open separate issues for bugs detected, use this issue for comments about the general progress in the release work. 

edit1: the 'give me a few days..' and the 'try to fix..' were in the same paragraph, which could be interpreted as I will do the fixing. That's not the case, so I separated them to be more clear.

**Comment by ccanepa** [comment]
Ok, no problem with custom clocks, I merged for easier work on issues
Merged Richard PR #319 (thanks Richard!)

A first run with recon.py shows tracebacks running some cocos/test, will fill separate issues.

I still need to compare images with previous cocos release to see if something more is broken; if something comes from that I will open separate issues.

@r1chardj0n3s 
could you update CHANGELOG for your changes ?

**Comment by ccanepa** [comment]
Edited the first post because it could be read as I will fix bugs discovered by my testing. That's not the case. I was only offering discovery, and __some__ eventual work on issues.

I know I will have little time to work on cocos issues.

What do you ( @r1chardj0n3s , @dangillet) think about:
  - move all the pyglet compatibity to a branch
  - reset master to before that
  - change setup.py to require pyglet==1.3.2
  - add pyglet version check in `cocos.__init__` and terminate if 1.4
  - release that as cocos 0.6.6 so that pip install delivers a working cocos
  - when the compatibilty pyglet 1.4 branch is done, release  

Reason: 
 - Current master, and current released in pypi don't work with 1.4 
 - I received yesterday an email anouncing pyweek to be September 22
 - Why inconvenience people if we can easily take care ?

**Comment by r1chardj0n3s** [comment]
That sounds good. I also struggle to find the time :)

**Comment by ccanepa** [comment]
done.

**Comment by ccanepa** [comment]
the work toward next release is in branch cocos2019

**Comment by ccanepa** [comment]
waiting for pyglet 1.4.3 release

**Comment by ccanepa** [comment]
the release cocos 0.6.7 was done some time ago, to close the issue only remains to update website (I need to get new credentials)
