### ISSUE TITLE
Make it possible to create CocosNodes without initialising the director

### ISSUE THREAD

**Issue by MartinHowarth** [los-cocos/cocos#331]
This is to allow non-gui testing of cocosnode functionaliy (and subclasses in downstream users code).

I've got a PR for this, will update momentarily.

**Comment by ccanepa** [comment]
One way to test without gui is the one used in repo\utest, have you seen that?

Your proposed change, make camera a property lazy initialized, is not complex, but will add a call in each cocosnode when the scene draws. And calls are relativelly costly in python.

What if in your testing situation you do

```python
class FakeCamera:
  pass

import cocos.camera
cocos.camera.camera = FakeCamera
```
or similar?

**Comment by MartinHowarth** [comment]
Ok, you're right to be concerned about performance for such a core component - I'll just mock it out instead.
