### ISSUE TITLE
display glitches report

### ISSUE THREAD

**Issue by crixthegreat** [los-cocos/cocos#339]
hi guys,

I got a very strange display glitch to report. Here are the screenshots.

![1](https://user-images.githubusercontent.com/13827785/106423051-a6bbd180-649a-11eb-86e1-b7275ccae5c9.png)
![2](https://user-images.githubusercontent.com/13827785/106423054-a8859500-649a-11eb-9bbc-9451d90d3aa6.png)
![3](https://user-images.githubusercontent.com/13827785/106423057-a9b6c200-649a-11eb-9753-6a7db799235c.png)

The green lines flicker.

This happens when I run the program with my new laptop Lenovo T14.

I wrote the program on my last Laptop Microsoft Surface Pro5, which run with nothing wrong.

The version:
Python: 3.6.8 
cocos2d: 0.6.7

The laptop T14 video card:
Intel UHD Graphics
NVIDIA Geforce MX330

I've checked that the latest driver has been installed. 

Please anyone can give me some advice?

**Comment by ccanepa** [comment]
looks like a driver problem to me.

Intel integrated gpu usually have bad OpenGL support.

Can you make sure your program uses the   NVIDIA  gpu?

**Comment by crixthegreat** [comment]
> looks like a driver problem to me. Intel integrated gpu usually have bad OpenGL support. Can you make sure your program uses the NVIDIA gpu?


Thank you very much.  According to your advice, I managed to change the default GPU to NVIDIA.  

The problem is solved.
