### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [los-cocos/cocos#344]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine cocos/custom_clocks.py and observe `unchedules`, however expect to see `unschedules`.
- Examine cocos/text.py and observe `undelying`, however expect to see `underlying`.
- Examine cocos/cocosnode.py and observe `calllbacks`, however expect to see `callbacks`.
- Examine utest/aux_RectMapCollider__no_stuck.py, utest/test_RectMapCollider__no_stuck.py and observe `parametrizable`, however expect to see `parameterizable`.
- Examine utest/aux_RectMapCollider__no_stuck.py, utest/test_RectMapCollider__no_stuck.py and observe `assings`, however expect to see `assigns`.
- Examine cocos/particle.py and observe `inconditionally`, however expect to see `unconditionally`.
- Examine benchmarks/collision/compare_collisions.py and observe `specifing`, however expect to see `specifying`.
- Examine cocos/actions/base_actions.py and observe `parameteres`, however expect to see `parameters`.
- Examine cocos/audio/pygame/mixer.py and observe `intialized`, however expect to see `initialized`.
- Examine test/test_shader_examples.py and observe `harcoded`, however expect to see `hardcoded`.
- Examine cocos/actions/instant_actions.py and observe `funtion`, however expect to see `function`.
- Examine cocos/particle.py and observe `diagonostic`, however expect to see `diagnostic`.
- Examine samples/jumping_lens.py and observe `decraese`, however expect to see `decrease`.
- Examine cocos/mapcolliders.py and observe `correctioin`, however expect to see `correction`.
- Examine cocos/skeleton.py and observe `betwen`, however expect to see `between`.
- Examine samples/mouse_elastic_box_selection.py and observe `aproach`, however expect to see `approach`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/cocos/pull/new/bugfix_typos

Thanks.

**Comment by ccanepa** [comment]
Merged, thank you.
