### ISSUE TITLE
add()'s problem

### ISSUE THREAD

**Issue by ruichen0** [los-cocos/cocos#351]
When I try to add()"(news.py):

class News(Sprite):
    def __init__(self):
        super(News, self).__init__(image=Image.news)
        self.do(Place((790, 520)))  
        self.image = Image.news

    def opacity(self):
        not_in_game = True  

        while True:
            if not not_in_game:
                Sprite.opacity = 255  
            elif not_in_game:
                Sprite.opacity = 0" 

"(main.py):
class Menu_Scene(Scene):
    def __init__(self):
        super().__init__()

        self.add(BackgroundLayer(), z=0)
        self.add(MenuLayer(), z=1)
        news = News
        news()

        button_batch = cocos.batch.BatchNode
        button_batch.position = 100, 100
        self.add(button_batch)
        button_batch.add(news())"

,there is a prompt of error like this:

" File "D:\source\main.py", line 25, in __init__
    button_batch.add(news())
TypeError: add() missing 1 required positional argument: 'child' "

May I know how to solve it?
Thanks a lot.

**Comment by ccanepa** [comment]
shoñdn't it be
````python
    button_batch = cocos.batch.BatchNode()
```

?
